import { theme as antdTheme, type ThemeConfig } from 'antd';
import { paletteFor, type Accent } from './palette.js';
import { dimensions, FONT_SANS, FONT_MONO } from './index.js';

export function createAppTheme({
  dark,
  accent,
  reducedMotion = false,
}: {
  dark: boolean;
  accent: Accent;
  reducedMotion?: boolean;
}): ThemeConfig {
  const c = paletteFor(dark, accent);
  const algorithm = dark ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm;
  const feedback = {
    colorSuccessBg: dark ? '#183629' : '#EBF7EE',
    colorSuccessBgHover: dark ? '#20452F' : '#D9EFDF',
    colorSuccessBorder: dark ? '#3D8454' : '#92BFA0',
    colorWarningBg: dark ? '#43291D' : '#FFF1E8',
    colorWarningBgHover: dark ? '#523525' : '#FFE1CB',
    colorWarningBorder: dark ? '#A16842' : '#C49C80',
    colorErrorBg: dark ? '#40232F' : '#FFF0F2',
    colorErrorBgHover: dark ? '#522C3B' : '#FFDFE5',
    colorErrorBorder: dark ? '#9C5669' : '#D89AA6',
    colorInfoBg: dark ? '#20344F' : '#EDF4FF',
    colorInfoBgHover: dark ? '#294362' : '#DCEAFF',
    colorInfoBorder: dark ? '#527DAD' : '#95B5DF',
  };
  const statusScales = {
    green: {
      1: feedback.colorSuccessBg,
      3: feedback.colorSuccessBorder,
      6: c.success,
      7: c.success,
    },
    red: { 1: feedback.colorErrorBg, 3: feedback.colorErrorBorder, 6: c.error, 7: c.error },
    blue: { 1: feedback.colorInfoBg, 3: feedback.colorInfoBorder, 6: c.info, 7: c.info },
    orange: {
      1: feedback.colorWarningBg,
      3: feedback.colorWarningBorder,
      6: c.warning,
      7: c.warning,
    },
    gold: {
      1: feedback.colorWarningBg,
      3: feedback.colorWarningBorder,
      6: c.warning,
      7: c.warning,
    },
    purple: {
      1: dark ? '#36264E' : '#F3EDFF',
      3: dark ? '#8765AD' : '#BAA0D9',
      6: dark ? '#D4B0FF' : '#7543BC',
      7: dark ? '#D4B0FF' : '#7543BC',
    },
  };
  // Ant Design emits both spellings into the same CSS variable. Set both from one source;
  // otherwise the generated alias overwrites the contrasted value in actual browser styles.
  const presetColors = Object.fromEntries(
    Object.entries(statusScales).flatMap(([color, levels]) =>
      Object.entries(levels).flatMap(([level, value]) => [
        [`${color}${level}`, value],
        [`${color}-${level}`, value],
      ]),
    ),
  );

  return {
    cssVar: { prefix: 'ant' },
    // Ant Design remaps seed colors in dark mode. These are already designed for that mode,
    // so retain the intended fills and links after generating the remaining component scales.
    algorithm: (seed, map) => ({
      ...algorithm(seed, map),
      colorPrimary: c.primary,
      colorLink: c.brandText,
      colorInfo: c.info,
      colorSuccess: c.success,
      colorWarning: c.warning,
      colorError: c.error,
    }),
    token: {
      motion: !reducedMotion,
      colorBgBase: dark ? c.page : c.surface,
      colorBgLayout: c.page,
      colorBgContainer: c.surface,
      colorBgElevated: c.surfaceRaised,
      colorBorder: c.borderStrong,
      colorBorderSecondary: c.border,
      colorText: c.text,
      colorTextSecondary: c.textSecondary,
      colorTextTertiary: c.textMuted,
      colorTextQuaternary: c.textMuted,
      colorTextDescription: c.textSecondary,
      colorTextPlaceholder: c.textMuted,
      colorTextDisabled: c.textMuted,
      colorFill: c.fill,
      colorFillSecondary: c.fill,
      colorFillTertiary: c.hover,
      colorFillQuaternary: c.page,
      colorFillAlter: c.tableHead,
      colorBgContainerDisabled: c.fill,
      colorPrimary: c.primary,
      colorPrimaryHover: c.primaryHover,
      colorPrimaryActive: c.primaryActive,
      colorPrimaryText: c.brandText,
      colorPrimaryTextHover: c.brandText,
      colorPrimaryTextActive: c.brandText,
      colorPrimaryBg: c.selected,
      colorPrimaryBgHover: c.selectedHover,
      colorPrimaryBorder: c.brandBorder,
      colorPrimaryBorderHover: c.brandText,
      colorLink: c.brandText,
      colorLinkHover: c.brandText,
      colorLinkActive: c.brandText,
      colorTextLightSolid: c.onPrimary,
      controlOutline: c.brandBorder,
      controlItemBgHover: c.hover,
      controlItemBgActive: c.selected,
      controlItemBgActiveHover: c.selectedHover,
      controlItemBgActiveDisabled: c.fill,
      colorSuccess: c.success,
      colorSuccessText: c.success,
      colorWarning: c.warning,
      colorWarningText: c.warning,
      colorError: c.error,
      colorErrorText: c.error,
      colorErrorHover: c.errorHover,
      colorErrorActive: c.errorActive,
      colorErrorTextHover: c.errorHover,
      colorErrorTextActive: c.errorActive,
      colorInfo: c.info,
      colorInfoText: c.info,
      fontFamily: FONT_SANS,
      fontFamilyCode: FONT_MONO,
      fontSize: 14,
      lineHeight: 1.5,

      borderRadius: 6,
      borderRadiusLG: 8,
      borderRadiusSM: 4,
      controlHeight: dimensions.control,
      controlHeightSM: dimensions.controlSmall,
      controlHeightLG: dimensions.touchTarget,
      fontSizeHeading1: dimensions.pageTitle,
      fontSizeHeading2: 22,
      fontSizeHeading3: 18,
      fontSizeHeading4: 16,
      fontSizeHeading5: 14,
      wireframe: false,

      // Depth is an interaction, not a default: nothing floats at rest.
      boxShadow: dark
        ? '0 1px 2px rgba(0, 0, 0, 0.5), 0 8px 24px -12px rgba(0, 0, 0, 0.7)'
        : '0 1px 2px rgba(24, 45, 54, 0.06), 0 12px 32px -16px rgba(24, 45, 54, 0.20)',
      boxShadowSecondary: dark
        ? '0 6px 20px -8px rgba(0, 0, 0, 0.7)'
        : '0 6px 20px -10px rgba(24, 45, 54, 0.16)',

      motionDurationMid: reducedMotion ? '0s' : `${dimensions.motion}ms`,
      ...feedback,
      ...presetColors,
    },
    components: {
      Layout: { bodyBg: c.page, siderBg: c.surface },
      Menu: {
        itemBg: 'transparent',
        subMenuItemBg: 'transparent',
        itemHeight: dimensions.control,
        itemMarginInline: 8,
        itemBorderRadius: 6,
        iconSize: 16,
        itemColor: c.text,
        itemSelectedBg: c.primary,
        itemSelectedColor: c.onPrimary,
        itemHoverBg: c.hover,
        itemHoverColor: c.text,
        itemActiveBg: c.selected,
        subMenuItemSelectedColor: c.brandText,
      },
      Card: {
        bodyPadding: 20,
        headerHeight: 48,
        headerFontSize: 16,
        colorBorderSecondary: c.border,
      },
      Table: {
        cellPaddingBlock: 12,
        cellPaddingInline: 16,
        cellPaddingBlockSM: 10,
        cellPaddingInlineSM: 12,
        headerBg: c.tableHead,
        headerColor: c.text,
        borderColor: c.border,
        rowHoverBg: c.hover,
        rowSelectedBg: c.selected,
        rowSelectedHoverBg: c.selectedHover,
        headerSortActiveBg: c.fill,
        headerSortHoverBg: c.hover,
      },
      Button: {
        fontWeight: 500,
        primaryShadow: 'none',
        defaultShadow: 'none',
        dangerShadow: 'none',
        primaryColor: c.onPrimary,
        dangerColor: dark ? c.page : c.surface,
        defaultBorderColor: c.borderStrong,
        defaultColor: c.text,
        defaultHoverColor: c.brandText,
        defaultHoverBorderColor: c.brandText,
        defaultActiveColor: c.brandText,
        defaultActiveBorderColor: c.brandText,
      },
      Input: {
        activeShadow: c.focusShadow,
        activeBorderColor: c.brandText,
        hoverBorderColor: c.brandText,
      },
      InputNumber: {
        activeShadow: c.focusShadow,
        activeBorderColor: c.brandText,
        hoverBorderColor: c.brandText,
      },
      Select: {
        optionSelectedBg: c.selected,
        optionSelectedColor: c.brandText,
        optionActiveBg: c.hover,
        activeBorderColor: c.brandText,
        hoverBorderColor: c.brandText,
      },
      DatePicker: {
        cellWidth: 32,
        cellHeight: 32,
        activeShadow: c.focusShadow,
        activeBorderColor: c.brandText,
        hoverBorderColor: c.brandText,
        cellRangeBorderColor: c.brandText,
      },
      Checkbox: {
        colorPrimary: c.brandText,
        colorPrimaryHover: c.brandText,
        colorWhite: dark ? c.onPrimary : c.surface,
      },
      Radio: {
        colorPrimary: c.brandText,
        colorPrimaryHover: c.brandText,
        colorWhite: dark ? c.onPrimary : c.surface,
        buttonSolidCheckedBg: c.primary,
        buttonSolidCheckedHoverBg: c.primaryHover,
        buttonSolidCheckedActiveBg: c.primaryActive,
      },
      Pagination: {
        colorPrimary: c.brandText,
        colorPrimaryHover: c.brandText,
        itemActiveBg: c.selected,
      },
      Segmented: {
        trackBg: c.fill,
        itemColor: c.textSecondary,
        itemHoverColor: c.text,
        itemHoverBg: c.hover,
        itemSelectedBg: c.selected,
        itemSelectedColor: c.brandText,
      },
      Tabs: {
        horizontalItemPadding: '12px 0',
        horizontalItemGutter: 24,
        titleFontSize: 14,
        itemColor: c.textSecondary,
        itemSelectedColor: c.brandText,
        itemHoverColor: c.brandText,
        itemActiveColor: c.brandText,
        inkBarColor: c.brandText,
      },
      Tag: {
        borderRadiusSM: 4,
        defaultBg: c.fill,
        defaultColor: c.textSecondary,
        colorTextLightSolid: dark ? c.page : c.surface,
      },
      Statistic: { contentFontSize: 26 },
      Modal: { borderRadiusLG: 12, titleFontSize: 18 },
      Drawer: { footerPaddingBlock: 16, footerPaddingInline: 20 },
      Badge: { colorTextLightSolid: dark ? c.page : c.surface },
      Tooltip: {
        colorBgSpotlight: dark ? c.surfaceRaised : c.text,
        colorTextLightSolid: dark ? c.text : c.surface,
      },
      Form: { itemMarginBottom: 20, verticalLabelPadding: '0 0 6px', labelColor: c.text },
      Descriptions: { labelColor: c.textSecondary },
    },
  };
}
